accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from accounts import views

urlpatterns = [
    url(r'^send_login_email', views.send_login_email, name='send_login_email'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),

]

lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
        url(r'^(\d+)/$',
            views.view_list, name='view_list'),
        url(r'^new$', views.new_list, name='new_list'),
]

superlists/urls.py
from django.conf.urls import url, include
from lists import views as list_views
from lists import urls as list_urls
from accounts import urls as account_urls

urlpatterns = [
        url(r'^$', list_views.home_page, name='home'),
        url(r'^lists/', include(list_urls)),
        url(r'^accounts/', include(account_urls)),
]

accounts/models.py
import uuid
from django.contrib import auth
from django.db import models

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)

class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True

class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/forms.py
from django import forms

from lists.models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)

        widgets = {
                'text': forms.fields.TextInput(attrs={
                    'placeholder': 'Enter a to-do item',
                    'class': 'form-control input-lg',
                    }),
                }

        error_messages = {
                'text': {'required': EMPTY_ITEM_ERROR},
                }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

accounts/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.contrib import auth, messages
from accounts.models import Token

def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)


    url = request.build_absolute_uri(reverse('login') + '?token=' + str(token.uid))
    message_body = f'Use this link to log in:\n\n{url}'

    send_mail('Your login link for Superlists', message_body, 'noreply@superlists', [email])

    messages.success(request,
            "Check your email, we've sent you a link you can use to log in.")
    return redirect('/')

def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from lists.models import Item, List
from lists.forms import ItemForm

# Create your views here.
def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ItemForm()
    if request.method == "POST":
        form = ItemForm(data=request.POST)
        if form.is_valid():
            form.save(for_list=list_)
            return redirect(list_)

    return render(request, 'list.html', {'list': list_, 'form': form, })

def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form": form})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>To-Do lists</title>
    <link href='/static/bootstrap/css/bootstrap.min.css' rel='stylesheet'>
    <link href='/static/base.css' rel='stylesheet'>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
        <div class="countainer-fluid">
          <a class="navbar-brand" href="/">Superlists</a>
          {% if user.email %}
          <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text">Logged in as {{ user.email }}</li>
            <li><a href="{% url 'logout' %}">Log out</a></li>
          </ul>
          {% else %}
          <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
            <span>Enter email to log in:</span>
            <input class="form-control" name="email" type="text" />
            {% csrf_token %}
          </form>
          {% endif %}
        </div>
      </nav>
      {% if messages %}
      <div class="row">
        <div class="col-md-8">
          {% for message in messages %}
          {% if message.level_tag == 'success' %}
          <div class="alert alert-success">{{ message }}</div>
          {% else %}
          <div class="alert alert-warning">{{ message }}</div>
          {% endif %}
          {% endfor %}
        </div>
      </div>
      {% endif %}
      <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
          <div class='text-center'>
            <h1>{% block header_text %}{% endblock %}</h1>
            <form method="POST" action="{% block form_action %}{% endblock %}">
            {{ form.text }}
            {% csrf_token %}
            {% if form.errors %}
            <div class="form-group has-error">
              <span class="help-block">{{ form.text.errors }}</span>
            </div>
            {% endif %}
            </form>
          </div>
        </div>
      </div>
      <div class='row'>
        <div class='col-md-6 col-md-offset-3'>
          {% block table %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %}Start a new To-Do list{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id='id_list_table' class='table'>
      {% for item in list.item_set.all %}
      <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
      {% endfor %}
    </table>
{% endblock %}